// This file is auto-generated by @hey-api/openapi-ts

export const TelemetryRecordSchema = {
    properties: {
        transformer_id: {
            type: 'string'
        },
        voltage_v: {
            type: 'number'
        },
        current_a: {
            type: 'number'
        },
        power_factor: {
            type: 'number'
        },
        frequency_hz: {
            type: 'number'
        },
        timestamp_epoch: {
            type: 'number'
        }
    },
    type: 'object',
    required: ['current_a', 'frequency_hz', 'power_factor', 'timestamp_epoch', 'transformer_id', 'voltage_v'],
    title: 'TelemetryRecord'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string'
        },
        token_type: {
            type: 'string',
            default: 'bearer'
        },
        expires_in: {
            type: 'integer',
            default: 3600
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'TokenResponse'
} as const;

export const UserAdminCreateSchema = {
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        is_active: {
            type: 'boolean',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'password'],
    title: 'UserAdminCreate'
} as const;

export const UserAdminUpdateSchema = {
    properties: {
        full_name: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_active: {
            oneOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_superuser: {
            oneOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [],
    title: 'UserAdminUpdate'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'password'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        is_active: {
            type: 'boolean'
        },
        is_superuser: {
            type: 'boolean'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'id', 'is_active', 'is_superuser'],
    title: 'UserRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        full_name: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [],
    title: 'UserUpdate'
} as const;