// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiV1AuthLoginLoginData, ApiV1AuthLoginLoginResponses, ApiV1AuthLogoutLogoutData, ApiV1AuthLogoutLogoutResponses, ApiV1AuthTokenTokenData, ApiV1AuthTokenTokenResponses, ApiV1TelemetryIngestIngestData, ApiV1TelemetryIngestIngestErrors, ApiV1TelemetryIngestIngestResponses, ApiV1UsersCreateUserAdminData, ApiV1UsersCreateUserAdminErrors, ApiV1UsersCreateUserAdminResponses, ApiV1UsersListUsersData, ApiV1UsersListUsersErrors, ApiV1UsersListUsersResponses, ApiV1UsersMeDeleteMeData, ApiV1UsersMeDeleteMeResponses, ApiV1UsersMeGetMeData, ApiV1UsersMeGetMeResponses, ApiV1UsersMePasswordUpdatePasswordMeData, ApiV1UsersMePasswordUpdatePasswordMeErrors, ApiV1UsersMePasswordUpdatePasswordMeResponses, ApiV1UsersMeUpdateMeData, ApiV1UsersMeUpdateMeErrors, ApiV1UsersMeUpdateMeResponses, ApiV1UsersRegisterRegisterData, ApiV1UsersRegisterRegisterErrors, ApiV1UsersRegisterRegisterResponses, ApiV1UsersSignupSignupData, ApiV1UsersSignupSignupErrors, ApiV1UsersSignupSignupResponses, ApiV1UsersUserIdDeleteUserData, ApiV1UsersUserIdDeleteUserErrors, ApiV1UsersUserIdDeleteUserResponses, ApiV1UsersUserIdGetUserByIdData, ApiV1UsersUserIdGetUserByIdErrors, ApiV1UsersUserIdGetUserByIdResponses, ApiV1UsersUserIdRoleUpdateUserRoleAdminData, ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors, ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses, ApiV1UsersUserIdUpdateUserAdminData, ApiV1UsersUserIdUpdateUserAdminErrors, ApiV1UsersUserIdUpdateUserAdminResponses, ApiV1UtilsHealthCheckHealthCheckData, ApiV1UtilsHealthCheckHealthCheckResponses, ApiV1UtilsTestEmailTestEmailData, ApiV1UtilsTestEmailTestEmailErrors, ApiV1UtilsTestEmailTestEmailResponses, HealthGetHealthData, HealthGetHealthResponses, HealthLiveGetLivenessData, HealthLiveGetLivenessResponses, HealthReadyGetReadinessData, HealthReadyGetReadinessResponses, HealthStartupGetStartupData, HealthStartupGetStartupResponses, MetricsMetricsEndpointData, MetricsMetricsEndpointResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Basic Health Status
 *
 * Returns standard healthy indicator.
 */
export const healthGetHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthGetHealthData, ThrowOnError>): RequestResult<HealthGetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthGetHealthResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/health',
    ...options
});

/**
 * Liveness Probe
 *
 * Kubernetes liveness check: immediate 200 if ASGI event loop is active.
 */
export const healthLiveGetLiveness = <ThrowOnError extends boolean = false>(options?: Options<HealthLiveGetLivenessData, ThrowOnError>): RequestResult<HealthLiveGetLivenessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthLiveGetLivenessResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/health/live',
    ...options
});

/**
 * Readiness Probe
 *
 * Deep dependency health check: verifies PostgreSQL and Valkey connectivity.
 */
export const healthReadyGetReadiness = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyGetReadinessData, ThrowOnError>): RequestResult<HealthReadyGetReadinessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthReadyGetReadinessResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/health/ready',
    ...options
});

/**
 * Startup Probe
 *
 * Validates that database migrations are executed and operational.
 */
export const healthStartupGetStartup = <ThrowOnError extends boolean = false>(options?: Options<HealthStartupGetStartupData, ThrowOnError>): RequestResult<HealthStartupGetStartupResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthStartupGetStartupResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/health/startup',
    ...options
});

/**
 * Prometheus Metrics
 *
 * Prometheus scrapable text exposition metric stream.
 */
export const metricsMetricsEndpoint = <ThrowOnError extends boolean = false>(options?: Options<MetricsMetricsEndpointData, ThrowOnError>): RequestResult<MetricsMetricsEndpointResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MetricsMetricsEndpointResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/metrics',
    ...options
});

/**
 * Obtain bearer token
 *
 * Exchange email/username + password for a signed JWT bearer token. Supports JSON & OAuth2 form.
 */
export const apiV1AuthLoginLogin = <ThrowOnError extends boolean = false>(options?: Options<ApiV1AuthLoginLoginData, ThrowOnError>): RequestResult<ApiV1AuthLoginLoginResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ApiV1AuthLoginLoginResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/auth/login',
    ...options
});

/**
 * Revoke bearer token
 *
 * Revoke the calling bearer token and invalidate in cache store.
 */
export const apiV1AuthLogoutLogout = <ThrowOnError extends boolean = false>(options?: Options<ApiV1AuthLogoutLogoutData, ThrowOnError>): RequestResult<ApiV1AuthLogoutLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ApiV1AuthLogoutLogoutResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/auth/logout',
    ...options
});

/**
 * OAuth2 Token Endpoint
 *
 * RFC 6749 standard OAuth2 /token endpoint for Swagger UI & automated tools.
 */
export const apiV1AuthTokenToken = <ThrowOnError extends boolean = false>(options?: Options<ApiV1AuthTokenTokenData, ThrowOnError>): RequestResult<ApiV1AuthTokenTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ApiV1AuthTokenTokenResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/auth/token',
    ...options
});

/**
 * List users (Admin)
 *
 * Superadmin endpoint to list all platform user records.
 */
export const apiV1UsersListUsers = <ThrowOnError extends boolean = false>(options?: Options<ApiV1UsersListUsersData, ThrowOnError>): RequestResult<ApiV1UsersListUsersResponses, ApiV1UsersListUsersErrors, ThrowOnError> => (options?.client ?? client).get<ApiV1UsersListUsersResponses, ApiV1UsersListUsersErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users',
    ...options
});

/**
 * Provision user (Admin)
 *
 * Superadmin endpoint to create a user with custom roles and superuser status.
 */
export const apiV1UsersCreateUserAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersCreateUserAdminData, ThrowOnError>): RequestResult<ApiV1UsersCreateUserAdminResponses, ApiV1UsersCreateUserAdminErrors, ThrowOnError> => (options.client ?? client).post<ApiV1UsersCreateUserAdminResponses, ApiV1UsersCreateUserAdminErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete own account
 *
 * Standard users can delete their own account. Superusers are forbidden.
 */
export const apiV1UsersMeDeleteMe = <ThrowOnError extends boolean = false>(options?: Options<ApiV1UsersMeDeleteMeData, ThrowOnError>): RequestResult<ApiV1UsersMeDeleteMeResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<ApiV1UsersMeDeleteMeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Get own profile
 *
 * Returns the profile of the currently authenticated user.
 */
export const apiV1UsersMeGetMe = <ThrowOnError extends boolean = false>(options?: Options<ApiV1UsersMeGetMeData, ThrowOnError>): RequestResult<ApiV1UsersMeGetMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ApiV1UsersMeGetMeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update own profile
 *
 * Update the authenticated user's full_name, email, or password.
 */
export const apiV1UsersMeUpdateMe = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersMeUpdateMeData, ThrowOnError>): RequestResult<ApiV1UsersMeUpdateMeResponses, ApiV1UsersMeUpdateMeErrors, ThrowOnError> => (options.client ?? client).patch<ApiV1UsersMeUpdateMeResponses, ApiV1UsersMeUpdateMeErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user (Admin)
 *
 * Superadmin endpoint to permanently remove a user account.
 */
export const apiV1UsersUserIdDeleteUser = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdDeleteUserData, ThrowOnError>): RequestResult<ApiV1UsersUserIdDeleteUserResponses, ApiV1UsersUserIdDeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<ApiV1UsersUserIdDeleteUserResponses, ApiV1UsersUserIdDeleteUserErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Get user details (Admin)
 *
 * Retrieve details of a user by UUID.
 */
export const apiV1UsersUserIdGetUserById = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdGetUserByIdData, ThrowOnError>): RequestResult<ApiV1UsersUserIdGetUserByIdResponses, ApiV1UsersUserIdGetUserByIdErrors, ThrowOnError> => (options.client ?? client).get<ApiV1UsersUserIdGetUserByIdResponses, ApiV1UsersUserIdGetUserByIdErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Update user details (Admin)
 *
 * Superadmin endpoint to assign roles, activate/deactivate accounts, or update profiles.
 */
export const apiV1UsersUserIdUpdateUserAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdUpdateUserAdminData, ThrowOnError>): RequestResult<ApiV1UsersUserIdUpdateUserAdminResponses, ApiV1UsersUserIdUpdateUserAdminErrors, ThrowOnError> => (options.client ?? client).patch<ApiV1UsersUserIdUpdateUserAdminResponses, ApiV1UsersUserIdUpdateUserAdminErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Open user registration
 *
 * Create a new standard (non-superuser) account. No JWT required.
 */
export const apiV1UsersRegisterRegister = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersRegisterRegisterData, ThrowOnError>): RequestResult<ApiV1UsersRegisterRegisterResponses, ApiV1UsersRegisterRegisterErrors, ThrowOnError> => (options.client ?? client).post<ApiV1UsersRegisterRegisterResponses, ApiV1UsersRegisterRegisterErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Open user signup
 *
 * Create a new standard (non-superuser) account. No JWT required.
 */
export const apiV1UsersSignupSignup = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersSignupSignupData, ThrowOnError>): RequestResult<ApiV1UsersSignupSignupResponses, ApiV1UsersSignupSignupErrors, ThrowOnError> => (options.client ?? client).post<ApiV1UsersSignupSignupResponses, ApiV1UsersSignupSignupErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update own password
 *
 * Change password for the currently authenticated user.
 */
export const apiV1UsersMePasswordUpdatePasswordMe = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersMePasswordUpdatePasswordMeData, ThrowOnError>): RequestResult<ApiV1UsersMePasswordUpdatePasswordMeResponses, ApiV1UsersMePasswordUpdatePasswordMeErrors, ThrowOnError> => (options.client ?? client).patch<ApiV1UsersMePasswordUpdatePasswordMeResponses, ApiV1UsersMePasswordUpdatePasswordMeErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update user role/status (Admin)
 *
 * Superadmin endpoint to assign roles, activate/deactivate accounts, or update profiles.
 */
export const apiV1UsersUserIdRoleUpdateUserRoleAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdRoleUpdateUserRoleAdminData, ThrowOnError>): RequestResult<ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses, ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors, ThrowOnError> => (options.client ?? client).patch<ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses, ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/users/{user_id}/role',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Bulk telemetry ingestion
 *
 * Accepts a list of TelemetryRecord objects. Records are bulk-inserted to PostgreSQL and the latest reading per unique transformer_id is written to Valkey.
 */
export const apiV1TelemetryIngestIngest = <ThrowOnError extends boolean = false>(options: Options<ApiV1TelemetryIngestIngestData, ThrowOnError>): RequestResult<ApiV1TelemetryIngestIngestResponses, ApiV1TelemetryIngestIngestErrors, ThrowOnError> => (options.client ?? client).post<ApiV1TelemetryIngestIngestResponses, ApiV1TelemetryIngestIngestErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/telemetry/ingest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Basic health check
 *
 * Lightweight ping endpoint.
 */
export const apiV1UtilsHealthCheckHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<ApiV1UtilsHealthCheckHealthCheckData, ThrowOnError>): RequestResult<ApiV1UtilsHealthCheckHealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ApiV1UtilsHealthCheckHealthCheckResponses, unknown, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/utils/health-check',
    ...options
});

/**
 * Test email delivery
 *
 * Dispatch a test transaction email to verify SMTP configuration.
 */
export const apiV1UtilsTestEmailTestEmail = <ThrowOnError extends boolean = false>(options: Options<ApiV1UtilsTestEmailTestEmailData, ThrowOnError>): RequestResult<ApiV1UtilsTestEmailTestEmailResponses, ApiV1UtilsTestEmailTestEmailErrors, ThrowOnError> => (options.client ?? client).post<ApiV1UtilsTestEmailTestEmailResponses, ApiV1UtilsTestEmailTestEmailErrors, ThrowOnError>({
    security: [{
            key: 'BearerAuth',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'OAuth2Password',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/api/v1/utils/test-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
