// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { HealthGetHealthError, HealthGetHealthResponse, HealthLiveGetLivenessError, HealthLiveGetLivenessResponse, HealthReadyGetReadinessError, HealthReadyGetReadinessResponse, HealthStartupGetStartupError, HealthStartupGetStartupResponse, MetricsMetricsEndpointError, MetricsMetricsEndpointResponse, ApiV1AuthTokenLoginError, ApiV1AuthTokenLoginResponse, ApiV1AuthLoginLoginError, ApiV1AuthLoginLoginResponse, ApiV1AuthLogoutLogoutError, ApiV1AuthLogoutLogoutResponse, ApiV1UsersListUsersData, ApiV1UsersListUsersError, ApiV1UsersListUsersResponse, ApiV1UsersCreateUserAdminData, ApiV1UsersCreateUserAdminError, ApiV1UsersCreateUserAdminResponse, ApiV1UsersUserIdGetUserByIdData, ApiV1UsersUserIdGetUserByIdError, ApiV1UsersUserIdGetUserByIdResponse, ApiV1UsersUserIdDeleteUserData, ApiV1UsersUserIdDeleteUserError, ApiV1UsersUserIdDeleteUserResponse, ApiV1UsersUserIdUpdateUserAdminData, ApiV1UsersUserIdUpdateUserAdminError, ApiV1UsersUserIdUpdateUserAdminResponse, ApiV1UsersMeGetMeError, ApiV1UsersMeGetMeResponse, ApiV1UsersMeUpdateMeData, ApiV1UsersMeUpdateMeError, ApiV1UsersMeUpdateMeResponse, ApiV1UsersRegisterRegisterData, ApiV1UsersRegisterRegisterError, ApiV1UsersRegisterRegisterResponse, ApiV1UsersUserIdRoleUpdateUserAdminData, ApiV1UsersUserIdRoleUpdateUserAdminError, ApiV1UsersUserIdRoleUpdateUserAdminResponse, ApiV1TelemetryIngestIngestData, ApiV1TelemetryIngestIngestError, ApiV1TelemetryIngestIngestResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Basic Health Status
 * Returns standard healthy indicator.
 */
export const healthGetHealth = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthGetHealthResponse, HealthGetHealthError, ThrowOnError>({
        ...options,
        url: '/health'
    });
};

/**
 * Liveness Probe
 * Kubernetes liveness check: immediate 200 if ASGI event loop is active.
 */
export const healthLiveGetLiveness = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthLiveGetLivenessResponse, HealthLiveGetLivenessError, ThrowOnError>({
        ...options,
        url: '/health/live'
    });
};

/**
 * Readiness Probe
 * Deep dependency health check: verifies PostgreSQL and Valkey connectivity.
 */
export const healthReadyGetReadiness = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthReadyGetReadinessResponse, HealthReadyGetReadinessError, ThrowOnError>({
        ...options,
        url: '/health/ready'
    });
};

/**
 * Startup Probe
 * Validates that database migrations are executed and operational.
 */
export const healthStartupGetStartup = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthStartupGetStartupResponse, HealthStartupGetStartupError, ThrowOnError>({
        ...options,
        url: '/health/startup'
    });
};

/**
 * Prometheus Metrics
 * Prometheus scrapable text exposition metric stream.
 */
export const metricsMetricsEndpoint = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<MetricsMetricsEndpointResponse, MetricsMetricsEndpointError, ThrowOnError>({
        ...options,
        url: '/metrics'
    });
};

/**
 * Obtain bearer token
 * Exchange email/username + password for a signed JWT bearer token. Supports JSON & OAuth2 form.
 */
export const apiV1AuthTokenLogin = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1AuthTokenLoginResponse, ApiV1AuthTokenLoginError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/token'
    });
};

/**
 * Obtain bearer token
 * Exchange email/username + password for a signed JWT bearer token. Supports JSON & OAuth2 form.
 */
export const apiV1AuthLoginLogin = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1AuthLoginLoginResponse, ApiV1AuthLoginLoginError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/login'
    });
};

/**
 * Revoke current session
 * Adds the current token's JTI to the Valkey revocation blocklist. Subsequent requests with the same token will be rejected with 401.
 */
export const apiV1AuthLogoutLogout = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1AuthLogoutLogoutResponse, ApiV1AuthLogoutLogoutError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/logout'
    });
};

/**
 * List users (Admin)
 * Superadmin endpoint to list all platform user records.
 */
export const apiV1UsersListUsers = <ThrowOnError extends boolean = false>(options?: Options<ApiV1UsersListUsersData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1UsersListUsersResponse, ApiV1UsersListUsersError, ThrowOnError>({
        ...options,
        url: '/api/v1/users'
    });
};

/**
 * Provision user (Admin)
 * Superadmin endpoint to create a user with custom roles and superuser status.
 */
export const apiV1UsersCreateUserAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersCreateUserAdminData, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1UsersCreateUserAdminResponse, ApiV1UsersCreateUserAdminError, ThrowOnError>({
        ...options,
        url: '/api/v1/users'
    });
};

/**
 * Get user details (Admin)
 * Superadmin endpoint to fetch details of any user by UUID.
 */
export const apiV1UsersUserIdGetUserById = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdGetUserByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1UsersUserIdGetUserByIdResponse, ApiV1UsersUserIdGetUserByIdError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/{user_id}'
    });
};

/**
 * Delete user (Admin)
 * Superadmin endpoint to permanently remove a user account.
 */
export const apiV1UsersUserIdDeleteUser = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdDeleteUserData, ThrowOnError>) => {
    return (options?.client ?? client).delete<ApiV1UsersUserIdDeleteUserResponse, ApiV1UsersUserIdDeleteUserError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/{user_id}'
    });
};

/**
 * Update user role/status (Admin)
 * Superadmin endpoint to assign roles, activate/deactivate accounts, or update profiles.
 */
export const apiV1UsersUserIdUpdateUserAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdUpdateUserAdminData, ThrowOnError>) => {
    return (options?.client ?? client).patch<ApiV1UsersUserIdUpdateUserAdminResponse, ApiV1UsersUserIdUpdateUserAdminError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/{user_id}'
    });
};

/**
 * Get own profile
 * Returns the profile of the currently authenticated user.
 */
export const apiV1UsersMeGetMe = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1UsersMeGetMeResponse, ApiV1UsersMeGetMeError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/me'
    });
};

/**
 * Update own profile
 * Update the authenticated user's full_name and/or password.
 */
export const apiV1UsersMeUpdateMe = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersMeUpdateMeData, ThrowOnError>) => {
    return (options?.client ?? client).patch<ApiV1UsersMeUpdateMeResponse, ApiV1UsersMeUpdateMeError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/me'
    });
};

/**
 * Open user registration
 * Create a new standard (non-superuser) account. No JWT required.
 */
export const apiV1UsersRegisterRegister = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersRegisterRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1UsersRegisterRegisterResponse, ApiV1UsersRegisterRegisterError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/register'
    });
};

/**
 * Update user role/status (Admin)
 * Superadmin endpoint to assign roles, activate/deactivate accounts, or update profiles.
 */
export const apiV1UsersUserIdRoleUpdateUserAdmin = <ThrowOnError extends boolean = false>(options: Options<ApiV1UsersUserIdRoleUpdateUserAdminData, ThrowOnError>) => {
    return (options?.client ?? client).patch<ApiV1UsersUserIdRoleUpdateUserAdminResponse, ApiV1UsersUserIdRoleUpdateUserAdminError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/{user_id}/role'
    });
};

/**
 * Bulk telemetry ingestion
 * Accepts a list of TelemetryRecord objects. Records are bulk-inserted to PostgreSQL and the latest reading per unique transformer_id is written to Valkey.
 */
export const apiV1TelemetryIngestIngest = <ThrowOnError extends boolean = false>(options: Options<ApiV1TelemetryIngestIngestData, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1TelemetryIngestIngestResponse, ApiV1TelemetryIngestIngestError, ThrowOnError>({
        ...options,
        url: '/api/v1/telemetry/ingest'
    });
};