// This file is auto-generated by @hey-api/openapi-ts

export type TelemetryRecord = {
    transformer_id: string;
    voltage_v: number;
    current_a: number;
    power_factor: number;
    frequency_hz: number;
    timestamp_epoch: number;
};

export type TokenResponse = {
    access_token: string;
    token_type?: string;
    expires_in?: number;
};

export type UserAdminCreate = {
    email: string;
    password: string;
    full_name: string;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type UserAdminUpdate = {
    full_name?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type UserCreate = {
    email: string;
    password: string;
    full_name: string;
};

export type UserRead = {
    id: string;
    email: string;
    full_name: string;
    is_active: boolean;
    is_superuser: boolean;
};

export type UserUpdate = {
    full_name?: (string | null);
    password?: (string | null);
};

export type HealthGetHealthResponse = ({
    [key: string]: (string);
});

export type HealthGetHealthError = unknown;

export type HealthLiveGetLivenessResponse = ({
    [key: string]: (string);
});

export type HealthLiveGetLivenessError = unknown;

export type HealthReadyGetReadinessResponse = ({
    [key: string]: unknown;
});

export type HealthReadyGetReadinessError = unknown;

export type HealthStartupGetStartupResponse = ({
    [key: string]: unknown;
});

export type HealthStartupGetStartupError = unknown;

export type MetricsMetricsEndpointResponse = (string);

export type MetricsMetricsEndpointError = unknown;

export type ApiV1AuthLoginLoginResponse = (TokenResponse);

export type ApiV1AuthLoginLoginError = unknown;

export type ApiV1AuthTokenLoginResponse = (TokenResponse);

export type ApiV1AuthTokenLoginError = unknown;

export type ApiV1AuthLogoutLogoutResponse = ({
    [key: string]: unknown;
});

export type ApiV1AuthLogoutLogoutError = unknown;

export type ApiV1UsersListUsersData = {
    query?: {
        limit?: number;
        offset?: number;
    };
};

export type ApiV1UsersListUsersResponse = (Array<UserRead>);

export type ApiV1UsersListUsersError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersCreateUserAdminData = {
    body: UserAdminCreate;
};

export type ApiV1UsersCreateUserAdminResponse = (UserRead);

export type ApiV1UsersCreateUserAdminError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersUserIdGetUserByIdData = {
    path: {
        user_id: string;
    };
};

export type ApiV1UsersUserIdGetUserByIdResponse = (UserRead);

export type ApiV1UsersUserIdGetUserByIdError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersUserIdDeleteUserData = {
    path: {
        user_id: string;
    };
};

export type ApiV1UsersUserIdDeleteUserResponse = ({
    [key: string]: (string);
});

export type ApiV1UsersUserIdDeleteUserError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersUserIdUpdateUserAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
};

export type ApiV1UsersUserIdUpdateUserAdminResponse = (UserRead);

export type ApiV1UsersUserIdUpdateUserAdminError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersMeGetMeResponse = (UserRead);

export type ApiV1UsersMeGetMeError = unknown;

export type ApiV1UsersMeUpdateMeData = {
    body: UserUpdate;
};

export type ApiV1UsersMeUpdateMeResponse = (UserRead);

export type ApiV1UsersMeUpdateMeError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersRegisterRegisterData = {
    body: UserCreate;
};

export type ApiV1UsersRegisterRegisterResponse = (UserRead);

export type ApiV1UsersRegisterRegisterError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1UsersUserIdRoleUpdateUserAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
};

export type ApiV1UsersUserIdRoleUpdateUserAdminResponse = (UserRead);

export type ApiV1UsersUserIdRoleUpdateUserAdminError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});

export type ApiV1TelemetryIngestIngestData = {
    body: Array<TelemetryRecord>;
};

export type ApiV1TelemetryIngestIngestResponse = ({
    [key: string]: unknown;
});

export type ApiV1TelemetryIngestIngestError = ({
    status_code: number;
    detail: string;
    extra?: {
        [key: string]: unknown;
    } | null;
});